name: nextcloud-wrapper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - pip:
    - typer[all]>=0.9.0
    - requests>=2.28.0
    - rich>=13.0.0
    - click>=8.0.0
    - black>=22.0.0
    - isort>=5.0.0
    - pytest>=7.0.0